In [1]:
import pandas as pd
from sql_data_service import SqlDataService

In [2]:
data_service = SqlDataService()

In [3]:
results = data_service.get_profiling_results()
bots = []
for r in results:
    data = {
        'id': r[0],
        'username': r[1],
        'bot_vector': r[2],
        'user_vector': r[3]
    }
    bots.append(data)

df = pd.DataFrame(bots)
df.to_csv('profiling_multiple.csv', index=False)
df.head(10)

,id,username,bot_vector,user_vector
0,1,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,0.2953946 0.2842729 0.2743393 0.2455520 0.3664...

In [4]:
results = data_service.get_recommendation_results()
actions = []
for r in results:
    data = {
        'user': r[0],
        'vector': r[1],
        'video_id': r[2],
        'categories': r[3],
        'action_type': r[4],
        'action_duration': r[5],
        'video_duration': r[6]
    }
    actions.append(data)

df = pd.DataFrame(actions)
df.to_csv('recommending_multiple.csv', index=False)
df.head(10)

,user,vector,video_id,categories,action_type,action_duration,video_duration
0,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,1,arts,,1500,50000
1,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,2,arts,,1590,53000
2,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,3,arts,,3700,37000
3,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,4,arts,,2310,33000
4,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,5,arts,,3480,58000
5,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,6,arts,,2880,48000
6,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,7,arts,,3000,30000
7,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,8,arts,,1850,37000
8,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,9,arts,,900,30000
9,bot1,0.1 0.1 0.1 0.1 0.3 0.1 0.7 0.1 0.5 0.1,10,arts,,2600,52000

In [5]:
results = data_service.get_training_set()
videos = []
for r in results:
    data = {
        'id': r[0],
        'title': r[1],
        'category': r[2],
        'duration': r[3],
        'tags': r[4],
        'publish_date': r[5],
        'vector': r[6]
    }
    videos.append(data)

df = pd.DataFrame(videos)
df.to_csv('videos_multiple.csv', index=False)
df.head(10)

,id,title,category,duration,tags,publish_date,vector
0,344,Video Title 344,arts chemistry,31000,,2023-12-31 15:55:32,1 0 0 1 0 0 0 0 0 0
1,1597,Video Title 1597,arts biology computer_science,59000,,2023-12-31 15:12:02,1 1 0 0 1 0 0 0 0 0
2,1356,Video Title 1356,literature psychology,53000,,2023-12-30 10:30:28,0 0 0 0 0 1 0 0 0 1
3,131,Video Title 131,computer_science,50000,,2023-12-29 09:08:39,0 0 0 0 1 0 0 0 0 0
4,3785,Video Title 3785,business mathematics physics,50000,,2023-12-28 04:09:55,0 0 1 0 0 0 1 0 1 0
5,2560,Video Title 2560,biology business chemistry,58000,,2023-12-27 08:35:17,0 1 1 1 0 0 0 0 0 0
6,1011,Video Title 1011,chemistry mathematics,59000,,2023-12-26 23:53:12,0 0 0 1 0 0 1 0 0 0
7,697,Video Title 697,biology music,31000,,2023-12-26 20:11:59,0 1 0 0 0 0 0 1 0 0
8,3021,Video Title 3021,biology computer_science physics,47000,,2023-12-26 06:46:51,0 1 0 0 1 0 0 0 1 0
9,985,Video Title 985,chemistry literature,49000,,2023-12-25 05:59:32,0 0 0 1 0 1 0 0 0 0